apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
  namespace: infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "9121"
      labels:
        app: redis
    spec:
      containers:
      - image: redis:5.0
        name: redis
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          periodSeconds: 10
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          periodSeconds: 10
          initialDelaySeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 6379
          protocol: TCP
      - image: bitnami/redis-exporter:1.3.4
        name: redis-exporter
        command:
        - /bin/bash
        - -c
        - redis_exporter --namespace=infra --redis.addr=localhost:6379
        ports:
        - containerPort: 9121
          protocol: TCP
